# Model arguments
# model_init_kwargs:
model_name_or_path: Qwen/Qwen3-4B-Instruct-2507 # change this
model_revision: main
torch_dtype: bfloat16
trust_remote_code: true
attn_implementation: flash_attention_2  #sdpa
# use_peft: True

# Data training arguments
system_prompt: SYSTEM_PROMPT_NORMAL # change this
dataset_mixer:
  "final_data/gpqa_formatted": 1.0
dataset_splits:
  - train
  - test
truncation_side: "left"
padding_side: "left"
preprocessing_num_workers: 5
wandb_project: "MAS"

# GRPO trainer config
# Output and Run Configuration
output_dir: saved/gpqa/grpo-two-stage-qwen3-4b-JP-TUNE-PRR # change this
add_peers: true
add_history_reasoning: false
add_current_reasoning: false
overwrite_output_dir: true
tag_prompt: "JP" #change this
run_name: grpo-two-stage-qwen3-4b-JP-TUNE-PRR #change this
report_to:
  - "tensorboard"
  # - "wandb"
save_strategy: "steps"
save_steps: 10
save_only_model: true
save_total_limit: 1
# resume_from_checkpoint: true

# Training Configuration
num_train_epochs: 1
max_steps: -1
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 3.0e-06
optim: adamw_torch
lr_scheduler_type: cosine
warmup_ratio: 0.1
max_grad_norm: 1.0
seed: 42
shuffle_dataset: false
bf16: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
beta: 0.1
num_iterations: 1
epsilon: 0.2
epsilon_high: 0.28
scale_rewards: true
loss_type: "dr_grpo"
mask_truncated_completions: true
use_liger_loss: false

# Evaluation Configuration
per_device_eval_batch_size: 8
eval_strategy: "steps"
eval_steps: 20
# eval_on_start: true

# Logging Configuration
logging_first_step: true
log_level: info
logging_steps: 10
logging_strategy: steps
log_completions: true
num_completions_to_print: 2
wandb_log_unique_prompts: true

# Generation Configuration
disable_dropout: true
max_prompt_length: 32768
max_completion_length: 6144
num_generations: 8
temperature: 0.9
top_p: 1.0
top_k: 50
repetition_penalty: 1.0
use_vllm: True
vllm_mode: "colocate"
vllm_gpu_memory_utilization: 0.25
vllm_tensor_parallel_size: 8
vllm_enable_sleep_mode: True
# vllm_guided_decoding_regex: <think>\n(.*?)\n</think>\n\n<answer>\n(.*?)\n</answer>